import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {fixtures,progress} from './fixtures.mjs';
const icon=readFileSync(new URL('../../assets/sol-erda.png',import.meta.url));
for(const job of ['hoyoung','ren'])test(job+' live Helper location, hover, click, preference and unsupported class',async({page},info)=>{
  await page.route('https://**/*',route=>route.fulfill({contentType:'image/png',body:icon}));
  const data=structuredClone(fixtures);
  data[job].model.nodes[1].helperExplanation='Helpful **detail**\nText <script>stays text</script>';
  await page.route('**/api/tracker-catalogue**',route=>{
    const selected=new URL(route.request().url()).searchParams.get('job')==='렌'?'ren':'hoyoung';
    return route.fulfill({json:data[selected].model});
  });
  await page.addInitScript(saves=>{for(const [key,value] of Object.entries(saves)){const name='hexa-tracker-'+key+'-v1';if(localStorage.getItem(name)===null)localStorage.setItem(name,JSON.stringify(value));}},progress);
  await page.goto('/');await page.locator('#class').selectOption(job);
  await expect(page.locator('[data-node]:visible').first()).toBeVisible();
  await page.locator('#view-infographic').click();
  const control=page.locator('#infographic-helper'),panel=page.locator('#helper-panel'),grid=page.locator('#infographic-grid');
  await expect(control).toBeChecked();await expect(panel).toBeVisible();
  await expect(panel.locator('[data-location]')).toHaveCount(18);
  const nextSkill=await grid.locator('[aria-current="step"]').getAttribute('data-skill');
  await expect(panel).toHaveAttribute('data-skill',nextSkill);
  const before=await page.evaluate(job=>localStorage.getItem('hexa-tracker-'+job+'-v1'),job);
  const previewSkill=data[job].model.nodes[1].short;
  const tiles=grid.locator('[data-skill="'+previewSkill+'"]');
  await tiles.first().hover();await expect(panel).toHaveAttribute('data-skill',previewSkill);
  await expect(grid.locator('.skill-hover')).toHaveCount(await tiles.count());
  await expect(panel.locator('.helper-explanation strong')).toHaveText('detail');
  await expect(panel.locator('.helper-explanation script')).toHaveCount(0);
  await expect(panel.locator('[data-target="true"]')).toHaveCount(1);
  expect(await page.evaluate(job=>localStorage.getItem('hexa-tracker-'+job+'-v1'),job)).toBe(before);
  await page.locator('.summary-heading h2').hover();await expect(panel).toHaveAttribute('data-skill',nextSkill);
  const first=grid.locator('[aria-current="step"]');
  const checkpoint=await first.getAttribute('data-checkpoint');
  await first.click();await page.locator('.summary-heading h2').hover();
  await expect(panel).toHaveAttribute('data-skill',await grid.locator('[aria-current="step"]').getAttribute('data-skill'));
  await grid.locator('[data-checkpoint='+JSON.stringify(checkpoint)+']').click();
  await page.locator('.summary-heading h2').hover();
  await expect(panel).toHaveAttribute('data-skill',nextSkill);
  await grid.locator('[data-skill="HEXA Stat II"]').first().hover();
  await expect(panel.locator('.helper-stat-icon')).toHaveAttribute('src','assets/hexa-stats/stat-2-unlocked.png');
  await expect(panel.locator('[data-location]')).toHaveCount(0);
  await page.locator('.summary-heading h2').hover();
  const geometry=await page.locator('.summary-body').evaluate(node=>({columns:getComputedStyle(node).gridTemplateColumns.split(' ').map(Number.parseFloat),width:document.documentElement.clientWidth,overflow:document.documentElement.scrollWidth}));
  expect(geometry.overflow).toBeLessThanOrEqual(geometry.width);
  if(info.project.name==='desktop'){expect(geometry.columns).toHaveLength(2);expect(Math.abs(geometry.columns[0]-geometry.columns[1])).toBeLessThan(1);}
  await page.screenshot({path:info.outputPath('helper-on.png'),fullPage:true});
  await control.uncheck();await expect(panel).toBeHidden();
  const off=await page.locator('.summary-metrics').evaluate(node=>({width:node.getBoundingClientRect().width,columns:getComputedStyle(node).gridTemplateColumns}));
  await tiles.first().hover();await expect(grid.locator('.skill-hover')).toHaveCount(await tiles.count());
  await page.reload();await expect(control).not.toBeChecked();await expect(panel).toBeHidden();
  expect(await page.locator('.summary-metrics').evaluate(node=>({width:node.getBoundingClientRect().width,columns:getComputedStyle(node).gridTemplateColumns}))).toEqual(off);
  await page.locator('#class').selectOption(job==='hoyoung'?'ren':'hoyoung');
  await expect(control).toBeDisabled();await expect(page.locator('#helper-support')).toContainText('Not supported');
  expect(await page.evaluate(()=>localStorage.getItem('hexa-tracker-helper-v1'))).toBe('false');
});
