import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import worker from '../worker.js';
import { currentDraft } from '../priority-draft.js';
import { NODES } from '../data.js';
import { mergeSkills, validateSkills, applySkills, validatePair, priorityGroups, orderMatches } from '../admin-panel-model.js';
const sqlite = new DatabaseSync(':memory:');
for(const file of ['0000_priority_preview.sql','0001_admin_skills.sql']) sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
const DB = {prepare(sql){let values=[];return {bind(...args){values=args;return this;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async first(){return sqlite.prepare(sql).get(...values)||null;},async run(){return sqlite.prepare(sql).run(...values);}};},async batch(statements){sqlite.exec('BEGIN');try{for(const statement of statements)await statement.run();sqlite.exec('COMMIT');}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
const env={DB,ADMIN_EMAIL:'owner@example.test'}, headers={'oai-authenticated-user-email':'owner@example.test','Content-Type':'application/json'};
const call=(method,value,owner=true)=>worker.fetch(new Request('https://test.example/api/admin-panel',{method,headers:owner?headers:{},...(value===undefined?{}:{body:JSON.stringify(value)})}),env);
const heroic=currentDraft('taotie_heroic'),interactive=currentDraft('taotie_interactive');
await DB.prepare('INSERT INTO priority_preview VALUES (?, ?, ?)').bind(heroic.mode,JSON.stringify(heroic),'old-date').run();
const original=sqlite.prepare('SELECT * FROM priority_preview').all();
for(const method of ['GET','POST','PUT','PATCH','DELETE']) assert.equal((await call(method,method==='GET'?undefined:{},false)).status,403);
const pair={id:'pair_test',name:'Ride or Die',region:'KMS',enabled:true,orders:{heroic,interactive}};
assert.equal((await call('POST',{...pair,orders:{heroic,interactive:{...interactive,steps:[]}}})).status,400);
assert.deepEqual(sqlite.prepare('SELECT * FROM priority_preview').all(),original);
assert.equal((await call('POST',pair)).status,200);
let state=await (await call('GET')).json();
assert.equal(Object.keys(state.drafts).length,3);assert.equal(priorityGroups(state.drafts).length,2);
assert.equal(state.drafts.pair_test_heroic.name,'Ride or Die | Heroic');
assert.equal(state.drafts.pair_test_interactive.name,'Ride or Die | Interactive');
assert.deepEqual(state.drafts.pair_test_heroic.steps,heroic.steps);
assert.equal((await call('POST',pair)).status,400);
assert.equal((await call('PATCH',{id:'pair_test',name:'New Name',enabled:false})).status,200);
state=await (await call('GET')).json();
assert(state.drafts.pair_test_heroic.name.startsWith('New Name'));
assert.equal(state.drafts.pair_test_interactive.enabled,false);
assert.deepEqual(state.drafts.pair_test_interactive.steps,interactive.steps);
assert(orderMatches(heroic.steps,'heroic',state.drafts).length===2);
const source={coreId:'masteryCore1',sourceName:'Source Harmony',icon:NODES.find(n=>n.short==='Harmony').icon};
let rows=mergeSkills({skills:[source]},[],state.drafts);assert.equal(rows[0].name,'Universal Harmony');
rows[0].name='Long edited name';rows[0].shortName='Short edited';rows[0].tag='M1';rows[0].category='Mastery';
rows=mergeSkills({skills:[source,{coreId:'skillCore99',sourceName:'New source',icon:'https://maplescouter.com/hexaskill/new.png'}]},rows,state.drafts);
assert.equal(rows[0].name,'Long edited name');assert.equal(rows[1].name,'');assert.equal(rows[1].category,'');
const review=validateSkills({job:'호영',rows});
assert.equal((await call('PUT',review)).status,200);
const publicState=await (await worker.fetch(new Request('https://test.example/api/priority-preview'),env)).json();
assert.equal(publicState.drafts.pair_test_heroic.names.Harmony,'Long edited name');assert.equal(publicState.drafts.pair_test_heroic.tags.Harmony,'M1');
assert.deepEqual(publicState.drafts.pair_test_heroic.steps,heroic.steps);
assert.equal(sqlite.prepare('SELECT draft_json FROM priority_preview WHERE mode = ?').get(heroic.mode).draft_json,original[0].draft_json);
assert.equal((await call('PUT',{...review,rows:[...rows,rows[0]]})).status,400);
assert.throws(()=>validateSkills({...review,rows:[{...rows[0],category:'HEXA Stat'}]}));
const differing={...heroic,names:{...heroic.names,Harmony:'Different name'}};
const conflicts=mergeSkills({skills:[source]},[],{a:heroic,b:differing});assert.equal(conflicts[0].name,'');assert.equal(conflicts[0].conflicts.length,2);
assert.equal((await call('DELETE',{id:'pair_test'})).status,200);
assert.deepEqual(sqlite.prepare('SELECT * FROM priority_preview').all(),original);
console.log('Admin skills, exact pair preservation, backup validation and atomic routes passed');
