import assert from 'node:assert/strict';
import {NODES} from '../data.js';
import {currentDraft,validateDraft} from '../priority-draft.js';
import {setTrackerCatalogue,rangeCost,combinedSourceGain,displayPriorityRows,matrixTotals} from '../planner.js';
import {extractScouterOrder} from '../scouter-extract.js';
import {capturedCatalogueCosts,applySkills} from '../admin-panel-model.js';
import {previewCatalog} from '../preview-priorities.js';
const node=NODES.find(node=>node.short==='Harmony');
const levels=Array.from({length:30},(_,i)=>({level:i+1,erda:i+2,frags:(i+1)**2+10}));
const catalogue={job:'호영',skills:[{coreId:'masteryCore1',sourceName:'Harmony',icon:node.icon,costs:{freeBaseLevel:0,levels}}],provenance:{costs:{url:'https://maplescouter.com/test.js',sha256:'a'.repeat(64),capturedAt:'2026-10-01T00:00:00Z'}}};
const capture=capturedCatalogueCosts(catalogue);
const response={class_hexa:[['Harmony',2,'/hexaskill/Hoyeong_2.png',5,25,5,25,1,0,'masteryCore1','0→2']]};
const extracted=extractScouterOrder(response,'lotus_heroic',{},capture.capturedCosts);
assert.equal(extracted.validation.issues.length,0,'Scouter nonuniform schedules validate without old Hoyoung costs');
const draft=validateDraft({...currentDraft('lotus_heroic'),...capture,steps:extracted.steps});
assert.equal(draft.steps[0].fdGain,0.833333);
assert.throws(()=>validateDraft({...draft,steps:[{...draft.steps[0],sourceCost:{from:0,erda:5,frags:24}}]}),/captured level schedule/);
assert.throws(()=>validateDraft({...draft,capturedCosts:{}}));
assert.throws(()=>validateDraft({...draft,capturedCosts:{Harmony:{...capture.capturedCosts.Harmony,levels:levels.slice(1)}}}));
assert.throws(()=>validateDraft({...draft,costProvenance:null}));
assert.throws(()=>validateDraft({...draft,capturedCosts:{Harmony:{freeBaseLevel:1,levels}}}));
// A later source and admin source refresh cannot alter either stored schedules or FD.
levels[0].frags=999;
assert.equal(draft.capturedCosts.Harmony.levels[0].frags,11);
const review={job:'호영',rows:[{coreId:'masteryCore1',source:catalogue.skills[0],name:'Reviewed name',shortName:'H',tag:'',category:'Mastery'}]};
const overlaid=applySkills({one:draft},review).one;
assert.deepEqual(overlaid.capturedCosts,draft.capturedCosts);
assert.deepEqual(overlaid.steps,draft.steps);
setTrackerCatalogue([{...node,costs:draft.capturedCosts.Harmony.levels,initialLevel:0}]);
assert.deepEqual(rangeCost('Harmony',0,2),{erda:5,frags:25});
const row=displayPriorityRows({Harmony:1},'lotus_heroic',draft.steps)[0];
assert.deepEqual(row.cost,{erda:3,frags:14});
const gain=combinedSourceGain(draft.steps,row,1);
assert(gain.estimated);
assert(Math.abs(gain.gain-((1+0.833333/100)**(14/25)-1)*100)<1e-9,'FD shares use this capture’s level costs');
assert.equal(matrixTotals({Harmony:1},'lotus_heroic',false,{},draft.steps).spent.frags,11);
const missing={...draft,steps:draft.steps.map(({fdFrom,fdGain,...step})=>step)};
assert.equal(previewCatalog({one:missing}).priorities[missing.mode][0].fdGain,undefined);
setTrackerCatalogue([{...node,costs:undefined}]);
assert.throws(()=>rangeCost('Harmony',0,1),/Missing cost/,'configured tracker cannot borrow a fixed table');
console.log('Capture-specific costs, immutable saved values, exact validation and FD shares passed');
