import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {NODES,STAT_ICONS} from '../data.js';
import {renDraftFromCapture,renCatalogueFromDrafts} from '../ren-priority.js';
import {reconstructScouterOrder,discoverySelection} from '../scouter-discovery.js';
import {currentDraft} from '../priority-draft.js';
import {validatePair} from '../admin-panel-model.js';
import {fragmentDays,fragmentDuration,fragmentCompletionDate,fragmentShortfall,effectiveDailyFragments,DUNGEON_WEEKLY_FRAGMENTS} from '../fragment-calculator.js';
assert.equal(fragmentShortfall(100,60),40);
assert.equal(fragmentShortfall(290,60),230);
assert.equal(fragmentShortfall(100,200),0);
for(const [dungeon,weekly] of Object.entries(DUNGEON_WEEKLY_FRAGMENTS)){
  for(const quest of [false,true])for(const farming of [0,10]){
    const rate=effectiveDailyFragments(farming,quest,dungeon);
    assert.equal(rate,farming+(weekly+(quest?90:0))/7);
    assert.equal(fragmentDays(290,60,rate),rate?230/rate:null);
  }
}
assert.ok(Math.abs(fragmentDays(290,60,effectiveDailyFragments(10,true,'nightmareParadise'))-7)<1e-12);
assert.equal(fragmentDays(100,200,10),0);
assert.equal(fragmentDays(100,200,0),null);
assert.equal(fragmentDuration(null,0),null);
assert.equal(fragmentDuration(14,0),'~2 weeks');
assert.equal(fragmentDuration(24.5,0),'~3.5 weeks');
assert.equal(fragmentDuration(7,0),'~1 week');
assert.equal(fragmentDuration(3.5,10),'3.5 days');
assert.equal(fragmentDuration(0,0),'~0 weeks');
const today=new Date(2026,9,2,23,59);
const localDate=(year,month,day)=>new Date(year,month,day).toLocaleDateString(undefined,{dateStyle:'medium'});
assert.equal(fragmentCompletionDate(12.3,today),localDate(2026,9,15));
assert.equal(fragmentCompletionDate(14,today),localDate(2026,9,16));
assert.equal(fragmentCompletionDate(0,today),localDate(2026,9,2));
assert.equal(fragmentCompletionDate(0.1,new Date(2026,11,31)),localDate(2027,0,1));
assert.equal(fragmentCompletionDate(null,today),null);
assert.equal(fragmentCompletionDate(NaN,today),null);
assert.equal(fragmentCompletionDate(1,new Date(2026,9,3)),localDate(2026,9,4));
const schedule={freeBaseLevel:0,levels:Array.from({length:30},(_,i)=>({erda:2,frags:i===9?100:i>9&&i<14?47.5:10}))};
// Integer level costs, checkpoint 10..14 sums to 290.
schedule.levels[10].frags=40;schedule.levels[11].frags=50;schedule.levels[12].frags=50;schedule.levels[13].frags=50;
const janus={freeBaseLevel:0,levels:Array.from({length:30},()=>({erda:1,frags:20}))};
const base={...currentDraft('lotus_heroic'),steps:[{skill:'Harmony',level:14,fdFrom:0,fdGain:1.25},{skill:'HEXA Stat I',level:20}],statIcons:STAT_ICONS,capturedCosts:{Harmony:schedule,Hecate:janus},costProvenance:{capturedAt:'2026-10-01T00:00:00Z',resources:[{url:'https://maplescouter.com/test.js',sha256:'a'.repeat(64)}]}};
const pair=id=>Object.fromEntries(validatePair({job:'호영',id,name:id,region:'GMS',enabled:true,orders:{heroic:base,interactive:base}}).map(d=>[d.mode,d]));
const drafts={...pair('pair_calc'),...pair('pair_other')};
const model={nodes:NODES.filter(n=>['Harmony','Hecate'].includes(n.short)).map(n=>({...n,sourceKey:n.short==='Hecate'?'generalCore2':'masteryCore1',costs:(n.short==='Harmony'?schedule:janus).levels})),stats:[{short:'HEXA Stat I',name:'HEXA Stat I',icon:STAT_ICONS['HEXA Stat I']}]};
const evidence=JSON.parse(readFileSync(new URL('../data/scouter-ren-kms-heroic-response-2026-10-01.json',import.meta.url)));
const renCatalogue={...evidence.catalogue,provenance:{costs:{...evidence.catalogue.provenance.costs,capturedAt:'2026-10-01T00:00:00Z'}}};
const candidate=reconstructScouterOrder(evidence.response,renCatalogue,discoverySelection('GMS','Heroic'),renCatalogue.sourceIconOverrides);
const renBase=renDraftFromCapture(candidate,renCatalogue);
const renDrafts=Object.fromEntries(validatePair({job:'렌',id:'pair_ren_calc',name:'Ren',region:'GMS',enabled:true,orders:{heroic:renBase,interactive:{...renBase,sourceMode:'ren_gms_interactive'}}}).map(d=>[d.mode,d]));
const renModel=renCatalogueFromDrafts(renDrafts);
const key='hexa-tracker-hoyoung-v1',renKey='hexa-tracker-ren-v1';let win;
async function boot(storage={}){
  if(win)await win.happyDOM.abort();win=new Window({url:'https://test.example/'});
  Object.defineProperty(win.navigator,'locks',{value:{request:(_name,run)=>run()}});
  win.document.write(readFileSync(new URL('../index.html',import.meta.url),'utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''));
  for(const k of ['window','document','location','localStorage','Event'])globalThis[k]=k==='window'?win:win[k];
  globalThis.Option=function(text,value){const o=document.createElement('option');o.textContent=text;o.value=value;return o;};
  for(const [k,v]of Object.entries(storage))localStorage.setItem(k,v);
  globalThis.fetch=async url=>{const ren=new URL(url,'https://test.example').searchParams.get('job')==='렌';return Response.json(url.startsWith('/api/tracker-catalogue')?(ren?renModel:model):{drafts:ren?renDrafts:drafts});};
  await import('../matrix-app.js?calc='+Math.random());await new Promise(r=>setTimeout(r,20));
}
const $=s=>document.querySelector(s);
const change=(s,value)=>{const el=$(s);if(el.type==='radio'&&value)document.querySelectorAll('input[type=radio]').forEach(other=>{if(other!==el&&other.name===el.name)other.checked=false;});if(el.type==='checkbox'||el.type==='radio')el.checked=value;else el.value=s==='#erdaRequest'?(value?'yes':'none'):value;el.dispatchEvent(new Event('change',{bubbles:true}));};
const state=()=>JSON.parse(localStorage.getItem(key));
const amounts=()=>[...document.querySelectorAll('#next-upgrade .material-amount[aria-label$="Fragments needed"]')].map(el=>el.querySelector('span').textContent);
const snapshot=()=>Object.fromEntries([key,renKey,'hexa-tracker-class-v1'].map(k=>[k,localStorage.getItem(k)]).filter(([,v])=>v));
await boot({[key]:JSON.stringify({mode:'pair_calc_heroic',levels:{Harmony:9},owned:60,perday:10})});
assert.equal($('.calculator-panel').hidden,false);
assert.doesNotMatch(document.body.textContent,/Estimates average weekly rewards/);
assert.equal($('#erdaRequest').value,'none');assert.equal($('#epicDungeon').value,'none');
assert.equal($('.calculator-title img').getAttribute('src'),'assets/sol-erda-fragment.png');
assert.equal($('.summary-panel').parentElement.className,'inputs');
assert.equal($('.summary-panel').nextElementSibling.querySelector('h2').textContent,'Current HEXA Matrix');
assert.equal($('#includeJanus').closest('.summary-panel'),$('.summary-panel'));
assert.equal($('#includeJanus').closest('.include-option').hidden,false);
assert.deepEqual(amounts(),['40','230']);
assert.equal($('.column-head'),null);
assert.match($('#next-upgrade').textContent,/Level 9 → 10/);
assert.match($('#next-upgrade').textContent,/Level 9 → 14 · Checkpoint/);
assert.equal($('#next-upgrade [data-next-level]').textContent,'Add 1 Level');
assert.equal($('#next-upgrade [data-upgrade-level="14"]').textContent,'Add to checkpoint');
assert.doesNotMatch($('#next-upgrade').outerHTML,/Fragments still needed/);
const fullTable=$('#priority').textContent,totals=$('#totals').textContent,completion=$('#completion').textContent,fd=$('#next-upgrade .fd-gain').textContent;
change('#erdaRequest',true);change('#epicDungeon','nightmareParadise');
assert.match($('#next-upgrade').textContent,/7.0 days/);
const remainingLabel=[...$('#totals').querySelectorAll('.material-amount')].at(-1).getAttribute('aria-label');
const remaining=Number(remainingLabel.split(' ')[0].replaceAll(',',''));
assert.match($('#time-estimate').textContent,new RegExp(fragmentDays(remaining,60,230/7).toFixed(1)+' days'));
assert.match($('#time-estimate').textContent,new RegExp(fragmentCompletionDate(fragmentDays(remaining,60,230/7))+' · '));
assert.equal($('#priority').textContent,fullTable);assert.equal($('#totals').textContent,totals);assert.equal($('#completion').textContent,completion);assert.equal($('#next-upgrade .fd-gain').textContent,fd);
change('#perday',0);assert.equal($('#time-estimate').hidden,false);
assert.match($('#next-upgrade').textContent,/~1.4 weeks/);
assert.doesNotMatch($('#next-upgrade').textContent,/ days/);
assert.match($('#time-estimate').textContent,new RegExp(fragmentDuration(fragmentDays(remaining,60,160/7),0)));
for(const [d,w]of Object.entries(DUNGEON_WEEKLY_FRAGMENTS)){
  change('#erdaRequest',false);change('#epicDungeon',d);
  assert.equal($('#time-estimate').hidden,w===0);
  if(w)assert.match($('#next-upgrade').textContent,new RegExp(fragmentDuration(230/(w/7),0)));
}
change('#erdaRequest',true);change('#epicDungeon','nightmareParadise');
change('#owned',10000);assert.deepEqual(amounts(),['0','0']);assert.match($('#next-upgrade').textContent,/~0 weeks/);
change('#owned',60);change('[name="world"][value="interactive"]',true);
assert.equal($('.calculator-panel').hidden,true);assert.equal($('#time-estimate').hidden,true);assert.equal($('#next-upgrade .material-days'),null);assert.equal(amounts().length,0);
assert.equal($('#includeJanus').closest('.include-option').hidden,false);
change('#includeJanus',true);assert.notEqual($('#totals').textContent,totals);assert.equal(state().owned,60);
change('[name="world"][value="heroic"]',true);assert.equal($('#erdaRequest').value,'yes');assert.equal($('#epicDungeon').value,'nightmareParadise');
change('#patch','pair_other');assert.equal(state().owned,60);assert.equal(state().epicDungeon,'nightmareParadise');
await boot(snapshot());assert.equal($('#owned').value,'60');assert.equal($('#erdaRequest').value,'yes');assert.equal($('#epicDungeon').value,'nightmareParadise');
const hyState=structuredClone(state());change('#class','ren');await new Promise(r=>setTimeout(r,20));
assert.equal($('#erdaRequest').value,'none');assert.equal($('#epicDungeon').value,'none');change('#owned',7);change('#epicDungeon','highMountain');
change('#class','hoyoung');await new Promise(r=>setTimeout(r,20));assert.deepEqual(state(),hyState);assert.equal($('#owned').value,'60');
$('#next-upgrade [data-next-level]').click();assert.equal(state().levels.Harmony,10);assert.equal(state().owned,60);
$('#next-upgrade [data-upgrade-level="14"]').click();assert.equal(state().levels.Harmony,14);assert.equal(state().owned,60);
change('[data-node="Janus"]',1);
change('[data-node="Harmony"]',30);change('[data-node="Janus"]',30);
assert.equal($('#total-remaining').hidden,true);
change('[data-node="Harmony"]',14);change('[data-node="Janus"]',1);
assert.equal($('#total-remaining').hidden,false);
assert.match($('#next-upgrade').textContent,/Unlock/);$('#next-upgrade [data-stat-action="unlock"]').click();assert.equal(state().owned,60);
assert.match($('#next-upgrade').textContent,/RNG/);assert.equal($('#next-upgrade .material-days'),null);assert.equal(amounts().length,0);
const input=$('[data-stat-line]');input.value=6;input.dispatchEvent(new Event('input',{bubbles:true}));assert.equal(state().owned,60);
assert.equal(JSON.parse(localStorage.getItem(renKey)).owned,7);
// Captured priorities omit Janus, but its input/save and optional totals remain.
await boot({[renKey]:JSON.stringify({mode:'pair_ren_calc_heroic',levels:{ren_generalCore1:7},includeJanus:false}),'hexa-tracker-class-v1':'ren'});
assert.equal($('[data-node-row="ren_generalCore1"]').hidden,false);
assert.equal($('[data-node="ren_generalCore1"]').value,'7');
assert.equal($('#includeJanus').disabled,false);
assert.equal($('#includeJanus').closest('.include-option').hidden,false);
const priorityBefore=$('#priority').innerHTML,nextBefore=$('#next-upgrade').innerHTML,totalsBefore=$('#totals').textContent;
change('#includeJanus',true);
assert.notEqual($('#totals').textContent,totalsBefore);
assert.equal($('#priority').innerHTML,priorityBefore);
assert.equal($('#next-upgrade').innerHTML,nextBefore);
assert.equal(JSON.parse(localStorage.getItem(renKey)).levels.ren_generalCore1,7);
change('[data-node="ren_generalCore1"]',8);
assert.equal(JSON.parse(localStorage.getItem(renKey)).levels.ren_generalCore1,8);
$('#undo-progress').click();
assert.equal($('[data-node="ren_generalCore1"]').value,'7');
$('#view-infographic').click();
assert.equal($('#includeJanus').closest('.include-option').hidden,false);
await boot(snapshot());
assert.equal($('[data-node="ren_generalCore1"]').value,'7');
assert.equal($('#includeJanus').checked,true);
for(const [number,name]of [[1,'HEXA Stat I'],[2,'HEXA Stat II'],[3,'HEXA Stat III']]){
  const selector=$(`[data-stat-selector="${name}"]`);
  assert.equal(selector.querySelector('img').getAttribute('src'),`assets/hexa-stats/stat-${number}-locked.png`);
  assert.ok(selector.querySelector('.stat-selector-name').classList.contains('visually-hidden'));
  assert.match(selector.querySelector('button').getAttribute('aria-label'),new RegExp(name));
}
await win.happyDOM.abort();console.log('Fragment calculator arithmetic and DOM checks passed');
