import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { Window } from 'happy-dom';
import worker from '../worker.js';
import { NODES } from '../data.js';
import { mergeSkills, validateSkills } from '../admin-panel-model.js';
import { helperExplanation, renderHelperExplanation } from '../helper-content.js';
import { renCatalogueFromDrafts } from '../ren-priority.js';

const window = new Window();
const box = window.document.createElement('div');
renderHelperExplanation(box,'First **bold**\n<script>alert(1)</script> **unfinished');
assert.equal(box.querySelector('strong').textContent,'bold');
assert.equal(box.querySelectorAll('br').length,1);
assert.equal(box.querySelector('script'),null);
assert(box.textContent.includes('<script>alert(1)</script> **unfinished'));
renderHelperExplanation(box,'  \r\n ');assert.equal(box.hidden,true);assert.equal(box.textContent,'');
assert.equal(helperExplanation(' A\r\nB\rC '),'A\nB\nC');
for(const value of [null,{},4,'x'.repeat(4001)])assert.throws(()=>helperExplanation(value));

const sqlite = new DatabaseSync(':memory:');
for(const file of ['0000_priority_preview.sql','0001_admin_skills.sql'])sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
const DB={prepare(sql){let values=[];return {bind(...args){values=args;return this;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async first(){return sqlite.prepare(sql).get(...values)||null;},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...values).changes)}};}};},async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
const env={DB,ADMIN_EMAIL:'owner@example.test'},headers={'oai-authenticated-user-email':env.ADMIN_EMAIL,'Content-Type':'application/json'};
const call=(method,value,path='/api/admin-panel',owner=true)=>worker.fetch(new Request('https://test.example'+path,{method,headers:owner?headers:{},...(value===undefined?{}:{body:JSON.stringify(value)})}),env);
const state=async()=> (await call('GET')).json();
const source={coreId:'masteryCore1',sourceName:'Harmony',icon:NODES.find(n=>n.short==='Harmony').icon,costs:{freeBaseLevel:0,levels:Array.from({length:30},(_,i)=>({level:i+1,erda:1,frags:10}))}};
const row={coreId:source.coreId,source,name:'Harmony',shortName:'Harmony',tag:'M1',category:'Mastery'};
const legacy={schema:1,job:'호영',rows:[row]};
sqlite.prepare('INSERT INTO admin_skills VALUES (?, ?, ?)').run(legacy.job,JSON.stringify(legacy),'old');
assert(!Object.hasOwn(validateSkills(legacy).rows[0],'helperExplanation'));
const explanation='First **bold**\nSecond <img src=x onerror=alert(1)>';
const initial=await state();
const review={...initial.skills,rows:[{...row,helperExplanation:explanation}],skillsRevision:initial.skillsRevision};
assert.equal((await call('PUT',review,'/api/admin-panel',false)).status,403);
assert.equal((await call('PUT',review)).status,200);
let saved=await state();assert.equal(saved.skills.rows[0].helperExplanation,explanation);
assert.equal((await call('PUT',{...review,rows:[{...row,helperExplanation:'stale'}]})).status,409);
assert.equal((await state()).skills.rows[0].helperExplanation,explanation);
// An old client with a fresh revision must not erase the new field.
assert.equal((await call('PUT',{...legacy,skillsRevision:saved.skillsRevision})).status,200);
saved=await state();assert.equal(saved.skills.rows[0].helperExplanation,explanation);
const catalogue=await (await call('GET',undefined,'/api/tracker-catalogue',false)).json();
assert.equal(catalogue.nodes[0].helperExplanation,explanation);
const refreshed=mergeSkills({skills:[{...source,sourceName:'Refreshed'}]},saved.skills.rows);
assert.equal(refreshed[0].helperExplanation,explanation);
const backup=await (await call('GET',undefined,'/api/admin-maintenance')).json();
assert.equal(JSON.parse(backup.skills[0].review_json).rows[0].helperExplanation,explanation);
sqlite.exec('DELETE FROM admin_skills');
assert.equal((await call('POST',{restoreSnapshot:backup})).status,200);
saved=await state();assert.equal(saved.skills.rows[0].helperExplanation,explanation);
const snapshot=sqlite.prepare('SELECT * FROM admin_skills').get();
for(const invalid of [null,{},'x'.repeat(4001)]) {
  assert.equal((await call('PUT',{...saved.skills,rows:[{...saved.skills.rows[0],helperExplanation:invalid}],skillsRevision:saved.skillsRevision})).status,400);
  assert.deepEqual(sqlite.prepare('SELECT * FROM admin_skills').get(),snapshot);
}
assert.equal((await call('PUT',{...saved.skills,rows:[{...saved.skills.rows[0],helperExplanation:'   '}],skillsRevision:saved.skillsRevision})).status,200);
assert.equal((await state()).skills.rows[0].helperExplanation,'');
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM priority_preview').get().n,0);
const renCatalogue=renCatalogueFromDrafts({ren:{job:'렌',sourceSkills:[source],capturedCosts:{ren_masteryCore1:{freeBaseLevel:0,levels:source.costs.levels}},statIcons:{'HEXA Stat I':source.icon}}},{rows:[{...row,helperExplanation:explanation},{coreId:'hexastat1',helperExplanation:'Stat **one**'}]});
assert.equal(renCatalogue.nodes[0].helperExplanation,explanation);assert.equal(renCatalogue.stats[0].helperExplanation,'Stat **one**');

// Actual Admin module: live preview, unsaved class retention and conflict handling.
const win=new Window({url:'https://test.example/priority-review.html'});
win.document.write(readFileSync(new URL('../priority-review.html',import.meta.url),'utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''));
for(const key of ['window','document','sessionStorage','Event'])globalThis[key]=key==='window'?win:win[key];
globalThis.Option=function(text,value){const option=document.createElement('option');option.textContent=text;option.value=value;return option;};
globalThis.fetch=async(url,options={})=>call(options.method || 'GET',options.body?JSON.parse(options.body):undefined,url);
await import('../priority-review.js?helper-content-test');
const settle=()=>new Promise(resolve=>setTimeout(resolve,30));
let input=document.querySelector('#skills textarea');assert(input);assert.equal(input.maxLength,4000);
input.value=explanation;input.dispatchEvent(new Event('input',{bubbles:true}));
assert.equal(document.querySelector('.helper-content-preview strong').textContent,'M1 · Harmony');
assert.equal(document.querySelector('.helper-content-preview>div:last-child strong').textContent,'bold');
assert.equal(document.querySelector('.helper-content-preview img[onerror]'),null);
document.querySelector('#ren-tab').click();await settle();document.querySelector('#hoyoung-tab').click();await settle();
assert.equal(document.querySelector('#skills textarea').value,explanation);
const peer=await state();peer.skills.rows[0].helperExplanation='Peer explanation';
assert.equal((await call('PUT',{...peer.skills,skillsRevision:peer.skillsRevision})).status,200);
document.querySelector('#save-skills').click();assert.equal(document.querySelector('#skills textarea').disabled,true);await settle();
assert.match(document.querySelector('#status').textContent,/changed in another tab/);
assert.equal(document.querySelector('#skills textarea').value,explanation);
assert.equal((await state()).skills.rows[0].helperExplanation,'Peer explanation');
globalThis.confirm=()=>true;document.querySelector('#load-latest-skills').click();await settle();
assert.equal(document.querySelector('#skills textarea').value,'Peer explanation');
input=document.querySelector('#skills textarea');input.value=explanation;input.dispatchEvent(new Event('input',{bubbles:true}));
document.querySelector('#save-skills').click();await settle();
assert.equal((await state()).skills.rows[0].helperExplanation,explanation);
assert.match(document.querySelector('#status').textContent,/Skills saved/);
console.log('Helper content: safe bold/lines, legacy omission, revisions, source refresh, public catalogue, backup/restore and explicit clear pass');
