import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {fixtures} from './browser/fixtures.mjs';
import {helperSupported,HELPER_PREFERENCE} from '../infographic-helper.js';
import {catalogueLocations} from '../helper-matrix.js';

assert.equal(helperSupported([{helperExplanation:' \n '}]),false);
assert.equal(helperSupported([{helperExplanation:'content'}]),true);
const model=structuredClone(fixtures.hoyoung.model);
const slots=catalogueLocations(model.nodes,new Set(['Harmony']));
assert.equal(slots.length,18);assert(slots.find(s=>s.id==='mastery_1').available);
assert.equal(slots.find(s=>s.id==='skill_3').available,false);
assert.throws(()=>catalogueLocations([{...model.nodes[0],group:'Mastery Nodes'}],new Set()));
let win;
const tick=()=>new Promise(resolve=>setTimeout(resolve,30));
async function boot(pref,unsupportedRen=true) {
  if(win)await win.happyDOM.abort();
  win=new Window({url:'https://test.example/'});
  Object.defineProperty(win.navigator,'locks',{value:{request:(_key,run)=>run()}});
  win.document.write(readFileSync(new URL('../index.html',import.meta.url),'utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''));
  for(const key of ['window','document','location','localStorage','Event'])globalThis[key]=key==='window'?win:win[key];
  globalThis.Option=function(text,value){const option=document.createElement('option');option.textContent=text;option.value=value;return option;};
  globalThis.confirm=()=>true;
  if(pref!==undefined)localStorage.setItem(HELPER_PREFERENCE,pref);
  const data=structuredClone(fixtures);
  data.hoyoung.model.nodes.find(n=>n.short==='Ascent').helperExplanation='Source **content**\n<script>text only</script>';
  if(!unsupportedRen)data.ren.model.nodes[0].helperExplanation='Ren content';
  globalThis.fetch=async url=>{const job=new URL(url,'https://test.example').searchParams.get('job')==='렌'?'ren':'hoyoung';return Response.json(url.startsWith('/api/tracker-catalogue')?data[job].model:{drafts:data[job].drafts});};
  await import('../matrix-app.js?helper-test='+Math.random());await tick();
  document.querySelector('#view-infographic').click();await tick();
}
await boot();
const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
assert.equal(q('#infographic-helper').checked,true);assert.equal(q('#helper-panel').hidden,false);
assert.equal(localStorage.getItem(HELPER_PREFERENCE),null,'default on must not write preference');
const next=()=>q('[data-checkpoint][aria-current="step"]');
assert.equal(q('#helper-panel').dataset.skill,next().dataset.skill);
assert.equal(q('.helper-explanation').hidden,true,'missing content still shows location/heading');
assert.equal(all('[data-location]').length,18);
const first=next(),skill=first.dataset.skill,initialSave=localStorage.getItem('hexa-tracker-hoyoung-v1');
const target=all('[data-checkpoint]').find(tile=>tile.dataset.skill==='Ascent');
target.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true}));
assert.equal(q('#helper-panel').dataset.skill,'Ascent');
assert.equal(all('.skill-hover').length,all('[data-checkpoint]').filter(tile=>tile.dataset.skill==='Ascent').length);
assert.equal(q('.helper-explanation strong').textContent,'content');assert.equal(q('.helper-explanation script'),null);
assert.equal(localStorage.getItem('hexa-tracker-hoyoung-v1'),initialSave,'hover must not write player progress');
q('#infographic-grid').dispatchEvent(new win.PointerEvent('pointerleave'));
assert.equal(q('#helper-panel').dataset.skill,skill);assert.equal(all('.skill-hover').length,0);
first.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true}));first.click();await tick();
assert.equal(q('#helper-panel').dataset.skill,next().dataset.skill,'click restores new actual next');
assert.equal(JSON.parse(localStorage.getItem('hexa-tracker-hoyoung-v1')).levels[skill],Number(first.querySelector('.checkpoint-level').textContent));
first.click();await tick();assert.equal(q('#helper-panel').dataset.skill,skill,'existing reverse Undo remains');
const stat=all('[data-checkpoint]').find(tile=>tile.dataset.skill==='HEXA Stat II');
stat.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true}));
assert(q('.helper-stat-icon').getAttribute('src').endsWith('stat-2-unlocked.png'));
assert.equal(all('#helper-panel [data-location]').length,0);
q('#infographic-grid').dispatchEvent(new win.PointerEvent('pointerleave'));
const beforeOff=localStorage.getItem('hexa-tracker-hoyoung-v1');
q('#infographic-helper').checked=false;q('#infographic-helper').dispatchEvent(new Event('change',{bubbles:true}));
assert.equal(q('#helper-panel').hidden,true);assert(!q('.summary-panel').classList.contains('helper-open'));
assert.equal(localStorage.getItem(HELPER_PREFERENCE),'false');assert.equal(localStorage.getItem('hexa-tracker-hoyoung-v1'),beforeOff);
target.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true}));assert(all('.skill-hover').length>0,'same-skill hover works with Helper off');
q('#class').value='ren';q('#class').dispatchEvent(new Event('change'));await tick();
assert.equal(q('#infographic-helper').disabled,true);assert.equal(q('#helper-panel').hidden,true);
assert.match(q('#helper-support').textContent,/Not supported/);assert.equal(localStorage.getItem(HELPER_PREFERENCE),'false');
await boot('false',false);assert.equal(q('#infographic-helper').checked,false);assert.equal(q('#helper-panel').hidden,true);
q('#class').value='ren';q('#class').dispatchEvent(new Event('change'));await tick();
assert.equal(q('#infographic-helper').disabled,false);assert.equal(q('#infographic-helper').checked,false);
await boot('true');assert.equal(q('#infographic-helper').checked,true);
// Finish everything through existing Tracker fields. Availability stays a location guide.
for(const input of all('[data-node]'))input.value=30;
q('[data-node]').dispatchEvent(new Event('input',{bubbles:true}));await tick();
for(const row of all('.stat-row')){
  const inputs=[...row.querySelectorAll('[data-stat-line]')];
  inputs.forEach(input=>{input.value=Number(input.dataset.lineIndex)===0?10:5;});
  inputs[0].dispatchEvent(new Event('input',{bubbles:true}));
}
assert.match(q('.helper-heading').textContent,/All priority steps complete/);
assert.equal(all('[data-location]').length,18);assert.equal(all('[data-target="true"]').length,0);
assert.equal(all('[data-location][data-available="true"]').length,13,'GMS catalogue availability plus Janus, never progress');
await win.happyDOM.abort();
console.log('Live Helper: supported/default/preference, missing content, mapping/locks, safe preview, hover restore, click/Undo, Stats, class switches, completion and unchanged progress pass');
