import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {fixtures} from './browser/fixtures.mjs';
import {helperSupported,HELPER_PREFERENCE} from '../infographic-helper.js';
import {catalogueLocations} from '../helper-matrix.js';

assert.equal(helperSupported([{helperExplanation:' \n '}]),false);
assert.equal(helperSupported([{helperExplanation:'content'}]),true);
const model=structuredClone(fixtures.hoyoung.model);
const slots=catalogueLocations(model.nodes,new Set(['Harmony']));
assert.equal(slots.length,18);assert(slots.find(s=>s.id==='mastery_1').available);
assert.equal(slots.find(s=>s.id==='skill_3').available,false);
assert.throws(()=>catalogueLocations([{...model.nodes[0],group:'Mastery Nodes'}],new Set()));
let win,media,mediaChange;
const tick=()=>new Promise(resolve=>setTimeout(resolve,30));
async function boot(pref,unsupportedRen=true) {
  if(win)await win.happyDOM.abort();
  win=new Window({url:'https://test.example/'});
  media={matches:true,addEventListener:(_event,callback)=>{mediaChange=callback;}};win.matchMedia=()=>media;
  Object.defineProperty(win.navigator,'locks',{value:{request:(_key,run)=>run()}});
  win.document.write(readFileSync(new URL('../index.html',import.meta.url),'utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''));
  for(const key of ['window','document','location','localStorage','Event'])globalThis[key]=key==='window'?win:win[key];
  globalThis.Option=function(text,value){const option=document.createElement('option');option.textContent=text;option.value=value;return option;};
  globalThis.confirm=()=>true;
  if(pref!==undefined)localStorage.setItem(HELPER_PREFERENCE,pref);
  const data=structuredClone(fixtures);
  data.hoyoung.model.nodes.find(n=>n.short==='Ascent').helperExplanation='Source **content**\n<script>text only</script>';
  if(!unsupportedRen)data.ren.model.nodes[0].helperExplanation='Ren content';
  globalThis.fetch=async url=>{const job=new URL(url,'https://test.example').searchParams.get('job')==='렌'?'ren':'hoyoung';return Response.json(url.startsWith('/api/tracker-catalogue')?data[job].model:{drafts:data[job].drafts});};
  await import('../matrix-app.js?helper-test='+Math.random());await tick();
  document.querySelector('#view-infographic').click();await tick();
}
await boot();
const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const dwell=()=>new Promise(resolve=>setTimeout(resolve,210));
const hover=async tile=>{tile.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true,pointerType:'mouse'}));await dwell();};
const leave=async()=>{q('#infographic-grid').dispatchEvent(new win.PointerEvent('pointerleave'));await dwell();};
assert(all('[data-checkpoint]').every(tile=>!tile.hasAttribute('title') && tile.getAttribute('aria-label').includes('level')),'native tooltip removed, accessible level/action retained');
assert.equal(q('#infographic-helper').checked,true);assert.equal(q('#helper-panel').hidden,true,'no guide at rest');
assert.equal(localStorage.getItem(HELPER_PREFERENCE),null,'default on must not write preference');
assert.equal(q('.summary-body'),null,'old Summary structure restored');
const first=q('[data-checkpoint][aria-current="step"]'),skill=first.dataset.skill,initialSave=localStorage.getItem('hexa-tracker-hoyoung-v1');
await hover(first);
assert.equal(q('#helper-panel').dataset.skill,skill);assert.equal(q('.helper-explanation').hidden,true,'blank content omitted');
assert.equal(all('[data-location]').length,18);
assert.deepEqual([...q('#helper-panel').children].map(n=>n.className),['helper-location','helper-heading','helper-explanation']);
await leave();assert.equal(q('#helper-panel').hidden,true);assert.equal(all('.skill-hover').length,0);
const target=all('[data-checkpoint]').find(tile=>tile.dataset.skill==='Ascent');
target.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true,pointerType:'mouse'}));
assert.equal(q('#helper-panel').hidden,true,'dwell avoids crossing flashes');await dwell();
assert.equal(q('#helper-panel').dataset.skill,'Ascent');
assert.equal(all('.skill-hover').length,all('[data-checkpoint]').filter(tile=>tile.dataset.skill==='Ascent').length);
assert.equal(q('.helper-explanation strong').textContent,'content');assert.equal(q('.helper-explanation script'),null);
assert.equal(localStorage.getItem('hexa-tracker-hoyoung-v1'),initialSave,'hover must not write progress');
target.dispatchEvent(new win.PointerEvent('pointerout',{bubbles:true,relatedTarget:q('#helper-panel')}));
q('#helper-panel').dispatchEvent(new win.PointerEvent('pointerenter'));await dwell();
assert.equal(q('#helper-panel').hidden,false,'popup remains readable when entered');
q('.helper-explanation').dispatchEvent(new win.Event('scroll',{bubbles:true}));assert.equal(q('#helper-panel').hidden,false,'popup scroll does not dismiss or reposition');
win.dispatchEvent(new win.Event('scroll'));assert.equal(q('#helper-panel').hidden,true,'page scrolling dismisses stale hover');
// A pending dwell is cancelled when leaving before it opens.
target.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true}));await leave();assert.equal(q('#helper-panel').hidden,true);
await hover(first);first.click();await tick();
assert.equal(q('#helper-panel').hidden,true,'click closes without following next');
assert.equal(JSON.parse(localStorage.getItem('hexa-tracker-hoyoung-v1')).levels[skill],Number(first.querySelector('.checkpoint-level').textContent));
first.click();await tick();assert.equal(JSON.parse(localStorage.getItem('hexa-tracker-hoyoung-v1')).levels[skill],JSON.parse(initialSave).levels[skill],'reverse Undo preserved');
const stat=all('[data-checkpoint]').find(tile=>tile.dataset.skill==='HEXA Stat II');await hover(stat);
assert.equal(q('.helper-location').hidden,true);assert.equal(q('.helper-stat-icon'),null);assert(q('.helper-heading img').getAttribute('src').endsWith('stat-2-unlocked.png'));assert.match(q('.helper-heading').textContent,/HEXA Stat II/);assert.equal(all('#helper-panel [data-location]').length,0);
document.dispatchEvent(new win.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(q('#helper-panel').hidden,true);
const beforeOff=localStorage.getItem('hexa-tracker-hoyoung-v1');
q('#infographic-helper').checked=false;q('#infographic-helper').dispatchEvent(new Event('change',{bubbles:true}));
assert.equal(localStorage.getItem(HELPER_PREFERENCE),'false');assert.equal(localStorage.getItem('hexa-tracker-hoyoung-v1'),beforeOff);
await hover(target);assert.equal(q('#helper-panel').hidden,true);assert(all('.skill-hover').length>0,'highlight works with Helper off');
q('#class').value='ren';q('#class').dispatchEvent(new Event('change'));await tick();
assert.equal(q('#infographic-helper').disabled,true);assert.equal(q('#helper-panel').hidden,true);
assert.match(q('#helper-support').textContent,/Not supported/);assert.equal(localStorage.getItem(HELPER_PREFERENCE),'false');
await boot('false',false);assert.equal(q('#infographic-helper').checked,false);assert.equal(q('#helper-panel').hidden,true);
q('#class').value='ren';q('#class').dispatchEvent(new Event('change'));await tick();assert.equal(q('#infographic-helper').disabled,false);assert.equal(q('#infographic-helper').checked,false);
await boot('true');const touch=all('[data-checkpoint]')[0];touch.dispatchEvent(new win.PointerEvent('pointerover',{bubbles:true,pointerType:'touch'}));await dwell();assert.equal(q('#helper-panel').hidden,true,'touch does not pin a guide');
await hover(touch);q('#view-tracker').click();await tick();assert.equal(q('#helper-panel').hidden,true,'view switch clears popup');
q('#view-infographic').click();await tick();assert.equal(q('#helper-panel').hidden,true);
await hover(all('[data-checkpoint]')[0]);
media.matches=false;mediaChange();assert(q('.helper-control').hidden);assert(q('#infographic-helper').disabled);assert(q('#helper-panel').hidden);
assert.equal(localStorage.getItem(HELPER_PREFERENCE),'true','losing hover capability preserves preference');
await hover(all('[data-checkpoint]')[0]);assert(q('#helper-panel').hidden);assert.equal(all('.skill-hover').length,0);
media.matches=true;mediaChange();assert(!q('.helper-control').hidden);assert(q('#infographic-helper').checked);assert(q('#helper-panel').hidden,'regaining hover does not open a guide');
await win.happyDOM.abort();
console.log('Hover Helper: dwell/exit/popup reading, safe content, Stats, no rest guide, click/Undo, preference/classes/touch/view switches and unchanged progress pass');
