import assert from 'node:assert/strict';
import {discoverSkillMetadata,discoverCostSchedules,discoverIconOverrides,inspectStatEvidence,discoverySelection,reconstructScouterOrder} from '../scouter-discovery.js';

// Synthetic fixtures exercise source syntax, not permanent job data or profiles.
const metadata='91178:(e,a,r)=>{let t={공용:{generalCore1:{title:"공용",url:"/hexaskill/General/General_1_0.png"}},"테스트":{skillCore1:{title:"원점",url:"/hexaskill/Test_1.png",resettable:!0},skillCore4:{title:"빈 슬롯",url:""}}}}';
const cat=discoverSkillMetadata(metadata,'테스트');
assert.equal(cat.skills.length,2);
assert.equal(cat.skills.find(s=>s.coreId==='skillCore1').tag,'Origin');
assert.equal(cat.skills[0].shared,true);
assert.equal(cat.placeholders.length,1);
assert.equal(discoverIconOverrides('R={generalCore2:"/hexaskill/General/General_2.png"}').generalCore2,'https://maplescouter.com/hexaskill/General/General_2.png');
assert.throws(()=>discoverIconOverrides('R={generalCore2:"/hexaskill/a.png"},T={generalCore2:"/hexaskill/b.png"}'),/Conflicting/);
assert.throws(()=>discoverSkillMetadata(metadata,'없는 직업'),/missing/);
assert.throws(()=>discoverSkillMetadata(metadata.replace('resettable:!0','resettable:process.exit()'),'테스트'),/literal/);
assert.throws(()=>discoverSkillMetadata(metadata.replace('Test_1.png','../Test_1.png'),'테스트'),/icon path/);
assert.throws(()=>discoverSkillMetadata(metadata.replace('title:"원점"','title:"원점",title:"중복"'),'테스트'),/Duplicate/);
const cumulative=Array.from({length:31},(_,i)=>i*i);
const costsSource=`60937:(e,a,r)=>{let a=[${cumulative}],b=[${cumulative.map(n=>n*3)}],p=[{key:"skillCore1",sole:a,piece:b,affectsSpec:!0,freeBaseLv:1},{key:"generalCore1",sole:a,piece:b,affectsSpec:!1}]}`;
const schedules=discoverCostSchedules(costsSource);
assert.deepEqual(schedules.skillCore1.levels[1],{level:2,erda:3,frags:9});
assert.equal(schedules.skillCore1.freeBaseLevel,1);
assert.equal(schedules.generalCore1.affectsBossing,false);
assert.throws(()=>discoverCostSchedules(costsSource.replace('freeBaseLv:1','freeBaseLv:2')),/baseline/);
assert.throws(()=>discoverCostSchedules(costsSource.replace('affectsSpec:!1','affectsSpec:false')),/syntax/);
assert.throws(()=>discoverCostSchedules(costsSource.replace('0,1,4','0,4,1')),/schedule/);
cat.skills.forEach(s=>s.costs=schedules[s.coreId]);
const selection=discoverySelection('KMS','Heroic');
assert.equal(selection.sole,false);
assert.equal(discoverySelection('GMS','Interactive').sole,true);
assert.throws(()=>discoverySelection('GMS','Reg'),/Choose/);
const response={standard:'dummy',patch:'test',hexa_updated:true,class_hexa:[['원점',3,'/hexaskill/Test_1.png',8,24,8,24,1.5,1.012,'skillCore1','원점 1→3']]};
const result=reconstructScouterOrder(response,cat,selection);
assert.deepEqual(result.issues,[]);
assert.equal(result.steps[0].from,1);
assert.equal(result.steps[0].fd.checkpointGainPercent,1.2);
assert.equal(result.publishable,false);
assert.deepEqual(result.reviewedOverrides,{});
const changed=structuredClone(response);changed.class_hexa[0][0]='다른 직업';changed.class_hexa[0][5]=9;
assert.deepEqual(reconstructScouterOrder(changed,cat,selection).issues.map(i=>i.kind),['cumulative-materials','response-identity']);
const fd=structuredClone(response);fd.class_hexa[0][7]={private:'must not leave'};
assert.equal(reconstructScouterOrder(fd,cat,selection).steps[0].fd.efficiencyPer30Fragments,null);
assert.throws(()=>reconstructScouterOrder({...response,standard:{}},cat,selection),/context/);
const stat={main_stat_level:9,sub_stat_level_1:5,sub_stat_level_2:6,stat_grade:20,slot_id:'0'};
const profile={userApiData:{info:{character_class:'테스트',character_level:260,character_name:'private'},hexaStat_opened:true},userStat:{isGMS:false,hexa:{hexaStat:3},account:'private'},userSpecialData:{userHexaStatData:[stat,stat,stat]}};
const evidence=inspectStatEvidence(profile,'테스트');
assert.equal(evidence.allThreeInvested,true);
assert.equal(evidence.backendResetProven,false);
assert.equal(JSON.stringify(evidence).includes('private'),false);
const empty=structuredClone(profile);empty.userStat.hexa.hexaStat=0;empty.userApiData.hexaStat_opened=false;empty.userSpecialData.userHexaStatData=[];
assert.equal(inspectStatEvidence(empty,'테스트').observedEmpty,true);
empty.userStat.isGMS=undefined;
assert.throws(()=>inspectStatEvidence(empty,'테스트'),/evidence/);
const statResponse={class_hexa:[['헥사스탯1',1,'https://open.api.nexon.com/static/maplestory/skill/icon/EXAMPLE',5,100,5,100,0.5,1.01,'hexaStat1','헥사스탯1 0→20']]};
assert.equal(reconstructScouterOrder(statResponse,cat,selection).steps[0].level,20);
assert.equal(reconstructScouterOrder(statResponse,cat,selection).steps[0].materialBasis,'RNG estimate');
console.log('Scouter discovery tests passed');

const mixedClass={...response,class:'테스트',character_class:'다른 직업'};
assert(reconstructScouterOrder(mixedClass,cat,selection).issues.some(i=>i.kind==='returned-class'&&i.field==='character_class'));
const drift=structuredClone(response);drift.class_hexa[0][10]='원점 0→3';
assert(reconstructScouterOrder(drift,cat,selection).issues.some(i=>i.kind==='transition-baseline'));
assert.throws(()=>reconstructScouterOrder(response,{...cat,selection:discoverySelection('GMS','Heroic')},selection),/selection/);
assert.throws(()=>reconstructScouterOrder(response,{...cat,skills:[...cat.skills,cat.skills[0]]},selection),/catalogue/);
const overflow=structuredClone(response);overflow.class_hexa[0][7]=Number.MAX_VALUE;
const overflowResult=reconstructScouterOrder(overflow,cat,selection);
assert.equal(overflowResult.steps[0].fd.checkpointGainPercent,null);
assert(overflowResult.issues.some(i=>i.kind==='invalid-fd-gain'));
const duplicateStat={class_hexa:[...statResponse.class_hexa,...statResponse.class_hexa]};
assert(reconstructScouterOrder(duplicateStat,cat,selection).issues.some(i=>i.kind==='transition-baseline'));

const {compareScouterCandidates}=await import('../scouter-comparison.js');
const unknown=compareScouterCandidates(result,result);
assert.equal(unknown.exactOrder,true);
assert.equal(unknown.contextComparable,false);
assert.equal(unknown.requiresReview,true);
assert.equal(unknown.contexts.find(c=>c.field==='patchVersion').status,'unknown');
const proven={...result,requestContext:{patchVersion:'test-1',benchmarkFingerprint:'a'.repeat(64),resetFingerprint:'b'.repeat(64)},provenance:{response:{capturedAt:'2026-09-30T00:00:00Z'}}};
const matched=compareScouterCandidates(proven,proven);
assert.equal(matched.contextComparable,true);
assert.equal(matched.fdComparable,true);
assert.equal(matched.requiresReview,false);
assert.equal(matched.publishable,false);
assert.equal(compareScouterCandidates({...proven,issues:[{kind:'response-identity'}]},proven).fdComparable,false);
assert.equal(compareScouterCandidates({...proven,issues:undefined},proven).requiresReview,true);
const renamed={...proven,reviewedOverrides:{skillCore1:{short:'edited',long:'private label'}}};
assert.deepEqual(compareScouterCandidates(proven,renamed),matched);
assert(!JSON.stringify(compareScouterCandidates(proven,renamed)).includes('private label'));
const otherWorld={...proven,selection:discoverySelection('KMS','Interactive')};
assert.equal(compareScouterCandidates(proven,otherWorld).contextComparable,false);
const anotherCharacter={...proven,requestContext:{...proven.requestContext,benchmarkFingerprint:'c'.repeat(64)}};
assert.equal(compareScouterCandidates(proven,anotherCharacter).contextComparable,false);
const changedFD=structuredClone(proven);changedFD.steps[0].fd.checkpointGainPercent=2;
assert(compareScouterCandidates(proven,changedFD).checkpointValues.some(v=>v.field==='fd'&&v.status==='different'));
assert.equal(compareScouterCandidates(proven,changedFD).fdComparable,true);
const changedOrder=structuredClone(proven);changedOrder.steps[0].level=4;
const ordered=compareScouterCandidates(proven,changedOrder);
assert.equal(ordered.exactOrder,false);
assert.equal(ordered.checkpointValues.length,0);
assert.equal(ordered.fdComparable,false);
assert.throws(()=>compareScouterCandidates({...proven,requestContext:{benchmarkFingerprint:'PRIVATE_CHARACTER'}},proven),/SHA-256/);
assert.throws(()=>compareScouterCandidates({...proven,provenance:{response:{capturedAt:'unknown'}}},proven),/capture/);
assert.throws(()=>compareScouterCandidates({...proven,steps:[{coreId:'edited alias',level:1}]},proven),/identity/);
console.log('Scouter comparison and reconstruction integrity tests passed');
